root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api_bin ."
  bin = "tmp/api_bin"
  full_bin = ""
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "static"]
  exclude_file = []
  exclude_regex = []
  delay = 1000
  stop_on_error = true
  poll = true
  poll_interval = 500